tools/noise/add-profile: Catch missing presets file early
This is required because all commands but the last in a pipe can't make
the script abort if they exit with a non-zero code.

diff --git a/tools/noise/add-profile b/tools/noise/add-profile
--- a/tools/noise/add-profile
+++ b/tools/noise/add-profile
@@ -64,6 +64,12 @@ fi
 # Main code.
 # --------------------------------------------------------------------
 
+if [ ! -f "$profile" ]; then
+	echo 1>&2
+	echo "Cannot open presets file: $profile" 1>&2
+	exit 1
+fi
+
 awk -f "$scriptdir/extract-values-from-presets.awk" < "$profile" | while read line; do
 	set -- $line
 	add_profile "$database" "$label_prefix" "$@"
