dt-curve-tool: helper script is smarter about dt-curve-tool path

diff --git a/tools/basecurve/dt-curve-tool-helper b/tools/basecurve/dt-curve-tool-helper
--- a/tools/basecurve/dt-curve-tool-helper
+++ b/tools/basecurve/dt-curve-tool-helper
@@ -7,6 +7,9 @@
 # As of this writing it can be found at http://www.gnu.org/licenses/gpl.txt
 #############################################################################
 
+_script_dir=$(dirname $0)
+_script_dir=$(cd "$_script_dir" && pwd -P)
+
 #############################################################################
 # Script vars
 #############################################################################
@@ -18,6 +21,7 @@ _raw=""
 _jpeg=""
 _args=""
 _state=""
+_dt_curve_tool=""
 
 #############################################################################
 # Script functions
@@ -29,10 +33,17 @@ cat <<EOF
 usage: dt-curve-tool-helper [OPTIONS] <RAW> [JPEG]
 
 OPTIONS:
--k, --keep    Keep intermediary PPM files (default: no)
+
+Standard
 -s, --state   dt-curve-tool state file path (default: program's default)
 -q, --quiet   Quiet mode, do not print final message (default: no)
 -h, --help    Print this help message
+
+Advanced
+-k, --keep                      Keep intermediary PPM files (default: no)
+    --dt-curve-tool-path <PATH> Path to dt-curve-tool binary
+                                (default: either found in PATH or same dir
+                                 as this script)
 EOF
 }
 
@@ -53,6 +64,10 @@ parse_args()
         -h|--help)
             print_help
             exit 0
+            ;;
+        --dt-curve-tool-path)
+            shift
+            _dt_curve_tool="$1"
             ;;
         *)
             _args="$_args $1"
@@ -133,6 +148,26 @@ generate_ppm_jpeg()
     convert $_transform "$_srcjpeg" "$_dst"
 }
 
+setup_dt_curve_tool()
+{
+    local _ret=0
+
+    if [ -z "$_dt_curve_tool" -o ! -x "$_dt_curve_tool" ] ; then
+        if [ -x "$_script_dir/dt-curve-tool" ] ; then
+            _dt_curve_tool="$_script_dir/dt-curve-tool"
+        else
+            _tmp=$(which dt-curve-tool)
+            if [ $? -eq 0 ] ; then
+                _dt_curve_tool="$_tmp"
+            else
+                _ret=1
+            fi
+        fi
+    fi
+
+    return $_ret
+}
+
 #############################################################################
 # Script starts here
 #############################################################################
@@ -149,6 +184,15 @@ setup_sources $_args
 # bail out if no raw
 if [ ! -f "$_raw" ] ; then
     printf "error: input raw file not found\n"
+    exit 1
+fi
+
+# find out our main tool
+setup_dt_curve_tool
+
+# bail out if tool not found
+if [ $? -ne 0 ] ; then
+    printf "error: dt-curve-tool not found\n"
     exit 1
 fi
 
@@ -202,7 +246,7 @@ if [ -n "$_state" ] ; then
 fi
 
 # analyze the images
-./dt-curve-tool $_state "$_ppm16" "$_ppm8"
+"$_dt_curve_tool" $_state "$_ppm16" "$_ppm8"
 if [ $_keep -eq 0 ] ; then
     rm -f "$_ppm16" "$_ppm8"
 fi
